### ISSUE TITLE
range query error

### ISSUE THREAD

**Issue by istrobes** [ryanfitz/vogels#102]
Hi, executing this example below throws an error `ExpressionAttributeNames can only be specified when using expressions` in 2.1.0 while working as expected in 2.0.0-rc10. Reverting for now.

```
var Joi    = require('joi');
var vogels = require('vogels');
var AWS    = require('aws-sdk');

var params = {
	"accessKeyId": "xxx",
	"secretAccessKey": "yyy",
	"endpoint": "http://192.168.99.100:18000",
	"region": "eu-west-1"
}

var dynamodb = new AWS.DynamoDB(params);
vogels.dynamoDriver(dynamodb);

var BlogPost = vogels.define('BlogPost', {
	"hashKey": "email",
	"rangeKey": "title",
	"schema": {
		"email": Joi.string().email(),
		"title": Joi.string()
	}
});

BlogPost
	.query('werner@vogels.com')
	.loadAll().exec(function(err, posts){
		console.log(err, posts);
	});
```

**Comment by istrobes** [comment]
I'm sorry to say this but in the latest release 2.1.2. I get exactly the same error using this example.

**Comment by ryanfitz** [comment]
@istrobes Could you turn on debugging and copy paste the output. 

You can enable debugging with:

```javascript
  var dynamodb = new AWS.DynamoDB(params);
  vogels.dynamoDriver(dynamodb);
  vogels.log.level('info');
```

**Comment by istrobes** [comment]
```
{"name":"vogels","hostname":"Iljas-MacBook-Pro-7.local","pid":54958,"model":"BlogPost","level":30,"params":{"ExpressionAttributeNames":{"#email":"email"},"ExpressionAttributeValues":{":email":"werner@vogels.com"},"KeyConditionExpression":"(#email = :email)","TableName":"blogposts"},"msg":"vogels QUERY request","time":"2015-11-17T22:35:05.207Z","v":0}
{"name":"vogels","hostname":"Iljas-MacBook-Pro-7.local","pid":54958,"model":"BlogPost","level":40,"err":{"message":"ExpressionAttributeNames can only be specified when using expressions","name":"ValidationException","stack":"ValidationException: ExpressionAttributeNames can only be specified when using expressions\n    at Request.extractError (/Users/ilja/Heroes/seamly-backend/node_modules/aws-sdk/lib/protocol/json.js:43:27)\n    at Request.callListeners (/Users/ilja/Heroes/seamly-backend/node_modules/aws-sdk/lib/sequential_executor.js:105:20)\n    at Request.emit (/Users/ilja/Heroes/seamly-backend/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\n    at Request.emit (/Users/ilja/Heroes/seamly-backend/node_modules/aws-sdk/lib/request.js:595:14)\n    at Request.transition (/Users/ilja/Heroes/seamly-backend/node_modules/aws-sdk/lib/request.js:21:10)\n    at AcceptorStateMachine.runTo (/Users/ilja/Heroes/seamly-backend/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /Users/ilja/Heroes/seamly-backend/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/Users/ilja/Heroes/seamly-backend/node_modules/aws-sdk/lib/request.js:37:9)\n    at Request.<anonymous> (/Users/ilja/Heroes/seamly-backend/node_modules/aws-sdk/lib/request.js:597:12)\n    at Request.callListeners (/Users/ilja/Heroes/seamly-backend/node_modules/aws-sdk/lib/sequential_executor.js:115:18)","code":"ValidationException"},"msg":"vogels QUERY error","time":"2015-11-17T22:35:05.283Z","v":0}
```

**Comment by ryanfitz** [comment]
@istrobes The query request data looks to be all correct. Have you tried hitting the real version of DynamoDB? I'm thinking this is possibly a bug with the version of dynamodb local you are using. This is the [closest thing](https://forums.aws.amazon.com/thread.jspa?threadID=181566) I've been able to find out about this error message. Can you try hitting a real DynamoDB table and/or make sure you are running the latest version of dynamodb local.

**Comment by istrobes** [comment]
Hi @ryanfitz 

Thank you for being so responsive! I will test against a real dynamo table tomorrow and get back to you!

Thanks,

I

**Comment by istrobes** [comment]
I can confirm this is working against the 'real' dynamodb service. However
this is also working when using 2.0.0-rc10 against the latest
dynamodb-local. Reverting for now until I have some time to investigate
this a bit further. Thanks!

**Comment by ryanfitz** [comment]
I had a feeling this would be an error with dynamodb local. To help with investigating -  the difference between rc10 and v2.1.2 is I've migrated all the api calls to the new expression apis. The previous apis are now marked as legacy by DynamoDB and will not be receiving new feature updates. I have a full suite of integration tests which run against a dynamodb local instance. I'm not sure why, but for some reason your instance of dynamodb local appears to be erroring out.

**Comment by istrobes** [comment]
Thanks! I will take a deeper look. FYI, the local instance I am using is
this one: https://hub.docker.com/r/deangiberson/aws-dynamodb-local/

**Comment by ryanfitz** [comment]
@istrobes If you want to try switching to using https://hub.docker.com/r/fitz/dynamodb-local/ That is the dynamodb local container that I use for testing against.

**Comment by istrobes** [comment]
Yes, indeed this in memory version seems to be working just fine! Thanks!
