### ISSUE TITLE
How to check table exits or not ?

### ISSUE THREAD

**Issue by osi-bhushankumar** [ryanfitz/vogels#105]
Hi,

I want to check whether 'table1' exits or not, how can I do that ?

**Comment by ryanfitz** [comment]
You can call `describeTable` on a model such as

```javascript
  Account = vogels.define('account', {hashKey : 'email', tableName: 'table1' });
  Account.describeTable( function (err, tableInfo) { ... } );
```

If you're looking to simply create a table if it does not already exist vogels provides a helper to create all non-existing tables.

```javascript
  vogels.createTables( function (err) { ... });
```
