### ISSUE TITLE
How can I do sorting with 'scan' queries ?

### ISSUE THREAD

**Issue by osi-bhushankumar** [ryanfitz/vogels#107]
Account
		  .scan()
		  .where('age').gte(21)
		  .exec();

Sometimes, their is not possible to fetch all data with hash key and range key. 

In above query I also want to perform sorting by 'email' or 'lastName' or 'age' or by using multiple properties, how can I do this ?

**Comment by ryanfitz** [comment]
DynamoDB does not support sorting by scan operations, you would have to load all items in memory and then sort them. 

`query` operations can be sorted and probably be more appropriate depending on your use case
