### ISSUE TITLE
autogenerated keys 

### ISSUE THREAD

**Issue by kzimnicki** [ryanfitz/vogels#112]
My situation is that i have object with autogenerated keys. 
```javascript
{
   k1: 'a',
   k2: 'b',
   kn: 'c'
}
```

I can't predict how many of them I will have and can't create schema for that, because vogels framework expect to declare all of keys. On other hand with JOI library this is possible (pattern):

```javascript
var schema = Joi.object().keys({
    username: Joi.string().required()
}).pattern(/\w+/, Joi.object());

Joi.validate({ username: 'abc', 'kn':{c:'g'} }, schema, function (err, value) {
    logger.info(err, value);
});
```
I would say the limitation is here: https://github.com/ryanfitz/vogels/blob/master/lib/schema.js#L105 that we can only use Joi.object().keys function. 

Possible solution will be a change of API to something like this: 
```javascript
var BlogPost = vogels.define('BlogPost', {
  hashKey : 'email',
  rangeKey : ‘title’,
  schema : Joi.object().keys({
    username: Joi.string().required()
}).pattern(/\w+/, Joi.object());
});
```

Is it possible ?

**Comment by viniciuskneves** [comment]
@kzimnicki have you tried to create your schema with https://github.com/hapijs/joi/blob/master/API.md#any ?

Because https://github.com/ryanfitz/vogels/blob/master/lib/schema.js#L105 checks if it is a plain object and Joi.any() isn't a plain object.

```
_.isPlainObject(Joi.any())
>false
```

**Comment by ryanfitz** [comment]
Dynamic keys are fully supported, see the [dynamic keys example](https://github.com/ryanfitz/vogels/blob/master/examples/dynamicKeys.js) for how to create a model where unknown keys are allowed. In the example only the `id` property is declared and any other key is allowed.
