### ISSUE TITLE
Incompatible with NodeJS 4 (and later)

### ISSUE THREAD

**Issue by ramondeklein** [ryanfitz/vogels#114]
After upgrading to NodeJS 4 it seems that the Vogels library doesn't deal with binary fields anymore. A binary field used to return a `Buffer` object, but now an `Array` object is returned. In NodeJS v0.x binary object were represented by the `Buffer` object. These objects are  backed by Typed Arrays, since NodeJS v4.

**Comment by ryanfitz** [comment]
what version of vogels are you running? We run our test suite against node v4 and v5

**Comment by ramondeklein** [comment]
I have created a small sample program that you can test. It runs fine with NodeJS 0.12.8, but it fails with NodeJS 4.2.2:

```
aws = require('aws-sdk');   /* v2.2.20 */
joi = require('joi');               /* 5.1.0 */
vogels = require('vogels'); /* 2.1.2 */

var region = 'eu-west-1';    /* USE YOUR REGION HERE */

aws.config.logger = process.stdout
aws.config.update({region: region});

var dynamo = new aws.DynamoDB({
  apiVersion: '2012-08-10',
  region: region
});

var model = vogels.define('test', {
  hashKey: 'id',
  timestamps: true,
  schema: {
    id: joi.binary(),
    test: joi.string()
  }
}, region);

var id = new Buffer([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]);

model.create({id: id, test: 'hello'}, function (err, data) {
  if (err) {
    return console.error('Error creating object: ' + err.message);
  }
  var newId = data.get('id');
  model.query(newId).exec(function(err, data) {
    if (err) {
      return console.error('Error creating object: ' + err.message);
    }
    console.log('Found ' + data.Items.length + ' items.');
    for (var i=0; i<data.Items.length; ++i) {
      console.log(i + ': ' + data.Items[i].get('test'));
    }
  });
});
```

Make sure that you have created the **tests** table in the proper region (I used eu-west-1) and you the AWS SDK can find the credentials to access this table.

**NodeJS 0.12.8 output**
```
[AWS dynamodb 200 0.175s 0 retries] putItem({ TableName: 'tests',
  Item: 
   { id: { B: <Buffer 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f 10> },
     test: { S: 'hello' },
     createdAt: { S: '2015-12-02T16:00:26.448Z' } } })
[AWS dynamodb 200 0.146s 0 retries] query({ ExpressionAttributeNames: { '#id': 'id' },
  ExpressionAttributeValues: { ':id': { B: <Buffer 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f 10> } },
  KeyConditionExpression: '(#id = :id)',
  TableName: 'tests' })
Found 1 items.
0: hello
```

**NodeJS 4.2.2 output**
```
[AWS dynamodb 400 0.183s 0 retries] putItem({ TableName: 'tests',
  Item: 
   { id: 
      { L: 
         [ { N: '1' },
           { N: '2' },
           { N: '3' },
           { N: '4' },
           { N: '5' },
           { N: '6' },
           { N: '7' },
           { N: '8' },
           { N: '9' },
           { N: '10' },
           { N: '11' },
           { N: '12' },
           { N: '13' },
           { N: '14' },
           { N: '15' },
           { N: '16' },
           [length]: 16 ] },
     test: { S: 'hello' },
     createdAt: { S: '2015-12-02T16:01:38.476Z' } } })
Error creating object: One or more parameter values were invalid: Type mismatch for key id expected: B actual: L
```

As you can see, the NodeJS 4 generates type **L**, where the old NodeJS generates type **B**.

**Comment by ryanfitz** [comment]
Thanks for the detailed example, I will take a deeper look into this as soon as I get a chance. My gut feeling is its a bug with the underlying aws-sdk, but can't say for sure just yet.

**Comment by ramondeklein** [comment]
I don't think it's an aws-sdk issue, because the following program runs fine with v0.12.8 and v4.2.2:
```
var AWS = require('aws-sdk'); /* v2.2.20 */

var region = 'eu-west-1';   /* Replace with your region */

AWS.config.logger = process.stdout;
AWS.config.update({region: region});

var docClient = new AWS.DynamoDB.DocumentClient({region: region});

var id = new Buffer([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]);
docClient.put({
    Item: {
        id: id,
        string: 'hello'
    },
    TableName: 'tests'
}, function(err, data){
  if (err) {
    return console.log(err);
  }
  docClient.get({
    Key: { id: id },
    TableName: 'tests'
  }, function(err, data){
    console.dir(data);
  });
});
```

Both versions give the following output:
```
[AWS dynamodb 200 2.02s 0 retries] putItem({ Item: 
   { id: { B: <Buffer 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f> },
     string: { S: 'hello' } },
  TableName: 'tests' })
[AWS dynamodb 200 0.105s 0 retries] getItem({ Key: { id: { B: <Buffer 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f> } },
  TableName: 'tests' })
{ Item: 
   { id: 
      Buffer {
        '0': 0,
        '1': 1,
        '2': 2,
        '3': 3,
        '4': 4,
        '5': 5,
        '6': 6,
        '7': 7,
        '8': 8,
        '9': 9,
        '10': 10,
        '11': 11,
        '12': 12,
        '13': 13,
        '14': 14,
        '15': 15 },
     string: 'hello' } }
```

**Comment by ramondeklein** [comment]
I have tracked down the issue. It is related to Lodash's merge function that has an issue on NodeJS 4. When it merges objects containing Buffers, then they are converted to arrays. See also this issue: https://github.com/lodash/lodash/issues/1453.

Unfortunately, the issue has been closed, but no new Lodash release has been released since then. I guess that we should upgrade Lodash when the issue is resolved.

**Comment by ryanfitz** [comment]
@ramondeklein thanks for tracking this down, lets keep this issue open till lodash gets a new release out.  I try to add integration tests any time bugs like this pop up, so Id also like to add some better testing around binaries.

**Comment by jdalton** [comment]
Lodash v4 will be release in mid Jan :)

**Comment by talolard** [comment]
Hey,
It seems like this fix wasn't pushed to npm. The latest version there still requires lodash 3.10.x

**Comment by ArVan** [comment]
Hello,
This issue isn't solved yet. Latest version of vogels uses lodash 3.10.x and has problems with storing binary.

Any possibility to upgrade?

**Comment by clarkie** [comment]
Have you tried https://github.com/clarkie/dynogels ?

**Comment by ArVan** [comment]
@clarkie No, I haven't. What're the key differences?

**Comment by clarkie** [comment]
I'm trying to keep dependencies up to date and fix any bugs but it's basically a fork of this repo.

**Comment by juanmanubens** [comment]
Hi, 

I had the same problem and it went away once I changed the code for loading IAM credentials - try to **configure the IAM settings without vogels.**

For reference, I have _vogels "^2.2.0"_ and _aws-sdk "^2.2.0"_ in my package.json

Avoid doing this:
`
vogels.AWS.config.update({region: region});
`

Instead, after loading vogels/joi/aws-sdk, try this:

`// Load IAM credentials`
`AWS.config.loadFromPath('./config.json');`

`// Use custom DynamoDB instance globally with all models`
`var dynamodb = new AWS.DynamoDB();`
`vogels.dynamoDriver(dynamodb);`
