### ISSUE TITLE
Let destroy implement the node pattern of function(err, result)

### ISSUE THREAD

**Issue by khebbie** [ryanfitz/vogels#115]
I spent quite some time wondering why I could not get a grip on destroying rows.

I use Q's nfcall which expects this signature: function(err, result). As I understand this is the standard in Node.
Most functions in vogels implements this pattern, but not `destroy`, which implements function(err).
Adding a simple overload would be fine, and the `result` parameter could simply expect a callback, that get a 'success' if row is deleted.

In order to adapt to promise I had to make this ugly piece of code (for a model called `Info`):

// adapt to promise, since it does not implement node conventions
Info.deleteEntry = function (hashKey) {

    var deferred = Q.defer();
    Info.destroy(hashKey, function (error, text) {
        if (error) {
            deferred.reject(new Error(error));
        } else {
            deferred.resolve(text);
        }
    });
    return deferred.promise;
   };
`

**Comment by ryanfitz** [comment]
Vogels does follow the signature `function(err, result)` for the `destroy` method. [Here](https://github.com/ryanfitz/vogels/blob/master/lib/table.js#L383-L393) is the callback implementation.
