### ISSUE TITLE
Feature request: deleteTable

### ISSUE THREAD

**Issue by rohithpr** [ryanfitz/vogels#116]
There doesn't seem to be a deleteTable option in vogels.

```
> vogels.deleteTable
undefined
> vogels.deleteTables
undefined
```

Or is it under some other name?

Also, [createTables](https://github.com/ryanfitz/vogels/blob/master/examples/createTable.js) isn't mentioned in the README.

**Comment by viniciuskneves** [comment]
Model.deleteTable

Where Model is any vogels.define

Does it help?

**Comment by rohithpr** [comment]
Oh! Cool. The two functions (create and delete) should probably be mentioned in the README!

**Comment by ryanfitz** [comment]
I try to make vogels as non-destructive as possibles so while there is a `createTables` helper there is not an equivalent `destroyTables`. However, as @viniciuskneves mentioned `Model.deleteTable` exists, as does `updateTable`

Happy to accept any PR's that help out with documentation.

**Comment by rohithpr** [comment]
@ryanfitz - I have made pull request for this. Is there a function to list all tables?
