### ISSUE TITLE
Ability to bind functions to returned objects

### ISSUE THREAD

**Issue by rickhuizinga** [ryanfitz/vogels#12]
It would be very useful to have the ability to bind functions to each object returned from a Model get/scan/query, similar to MongooseJS's (MongoDB ORM) instance methods: http://mongoosejs.com/docs/guide.html#methods

Vogels could allow methods to be added to a Model definition and then bind them to its returned objects using UnderscoreJS's bind method (http://underscorejs.org/#bind).

**Comment by tony-gutierrez** [comment]
Is there a way to access these in a "before" hook? For example, when hashPassword is prototyped onto the User model, I cannot access it like so:

```
User.before('create', function(user, cb) {
    if (user.password && user.passwordUpdated) {
      user.passwordUpdated = undefined;
      user.salt = crypto.randomBytes(16).toString('base64');
      user.password = user.hashPassword();
    }

    cb(null, user);
  });

```

**Comment by set-killer** [comment]
@tony-gutierrez there is [this example with the hooks...](https://github.com/ryanfitz/vogels/blob/master/examples/hooks.js)

**Comment by set-killer** [comment]
Have you tried with something like:

```
user.password = this.hashPassword(user.password);
```

**Comment by tony-gutierrez** [comment]
Yeah ,tried looking at user, User, this...nothing. I am guessing that the hooks just get the 'attrs' and not the full stack, so they cant access prototype methods.
