### ISSUE TITLE
BatchWriteItem feature request

### ISSUE THREAD

**Issue by foobar8675** [ryanfitz/vogels#120]
Are there plans to implement BatchWriteItem, opposed to saving in parallel?

**Comment by ryanfitz** [comment]
I would accept a PR of this. The main reason I haven't added batch write support is because I have found the `BatchWriteItem` api far too limiting to be useful for real applications.

**Comment by foobar8675** [comment]
I might be up for that, but can I ask what you found limiting about it?

**Comment by ryanfitz** [comment]
`BatchWriteItem` doesn't support conditions when adding / removing items. When deleting items it does not return the deleted item in the response. It consumes the same amount of write throughput as a regular putItem request. I believe `BatchWriteItem` is provided for bulk loading of data from another datastore into DynamoDB.

I should point out, vogels does support saving multiple items at once, with full support of conditions.

```javascript
  Model.create([item, item2, item3], function (err, items) { ... });
```

**Comment by foobar8675** [comment]
I see what you're saying and also the aws docs mention doing it just the way you implemented it. thanks for pointing out and writing this very nice library.
