### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by rvdwijngaard** [ryanfitz/vogels#126]
Is there any chance you will be providing a typescript definition file for this library?

**Comment by ryanfitz** [comment]
I'm not very familiar with Typescript so this isn't something Id want to have to attempt to add & maintain. It would make sense to create a separate project which maintains a Typescript definition file.

**Comment by madve2** [comment]
I think it's worth noting that the "successor" to this project, [dynogels](https://github.com/clarkie/dynogels) does have TS definition files at `@types/dynogels`.
