### ISSUE TITLE
Value 'BOOLEAN' failed to satisfy constraint

### ISSUE THREAD

**Issue by bendavis78** [ryanfitz/vogels#128]
I have a model defined with `Joi.boolean()`. When I try to create the table, I get this error:

```
Value 'BOOLEAN' at 'attributeDefinitions.3.member.attributeType' failed to satisfy constraint: Member must satisfy enum value set: [B, N, S]
```

**Comment by ryanfitz** [comment]
DynamoDB does not support bools for primary keys. Do to how Dynamo works a boolean is usually not a good choice for a key. However, we could return a clearer error.
