### ISSUE TITLE
How to skip first n record?

### ISSUE THREAD

**Issue by osi-bhushankumar** [ryanfitz/vogels#130]
Hi,

I am working on some pagination style record fetching UI, where I want to skip first 10 record or 20 record or 30 record. 

How can I do that ?

**Comment by ryanfitz** [comment]
This would be a bit more appropriate to ask on stackoverflow. I have an [answer](http://stackoverflow.com/a/34428286/4621778) to a similar pagination question over at stackoverflow. If you still have questions feel free to post a question to SO with some details of your data model and I'll be happy to help out.
