### ISSUE TITLE
Implement Exponential Backoff

### ISSUE THREAD

**Issue by bradgignac** [ryanfitz/vogels#133]
The DynamoDB documentation recommends implementing client-side retries with exponential backoff when a `ProvisionedThroughputExceededException` is received. My team
has already implemented this as a wrapper around Vogels, but we'd love  to push this feature down into Vogels if you're open to the contribution.

The model definition might be good place to enable this feature. For example:

``` javascript
var Account = vogels.define('Account', {
  hashKey : 'email',
  timestamps : true,
  retries: {
    initialDelay: 10,     // Start with a 10ms backoff.
    maxDelay: 10000       // Limit the max delay to 10s.
    maxAttempts: 10       // Never attempt more than 10 operations.
  },
  schema : {
    email   : Joi.string().email()
  }
});
```

When this flag is defined, the model should automatically retry all reads and writes in the event of a `ProvisionedThroughputExceededException` error. It will use full jitter exponential backoff as described by https://www.awsarchitectureblog.com/2015/03/backoff.html.

Any concerns with someone from my team proceeding with this implementation?

**Comment by ryanfitz** [comment]
Exponential backoff is already handled by the aws sdk. Are you looking for different ways of configuring how the sdk handles backoff?

Example:

``` javascript
var dynamo = new AWS.DynamoDB({ maxRetries: 2 });
vogels.dynamoDriver(dynamo);
```

**Comment by bradgignac** [comment]
@ryanfitz Somehow we missed this within the AWS SDK. Thanks!
