### ISSUE TITLE
Allow Joi options on validate

### ISSUE THREAD

**Issue by justhamade** [ryanfitz/vogels#134]
Currently there are no options passed to Joi validate.  It would be nice to be able to allow options on [validate](https://github.com/hapijs/joi/blob/v7.2.3/API.md#validatevalue-schema-options-callback) like allowUnknown or stripUnknown.  If I have time I will submit a PR.

**Comment by ryanfitz** [comment]
Most / all of the Joi validation options should already be configurable. 

For example to allow an object with unknown properties:

``` javascript
var Model = vogels.define('example-unknown-keys', {
  hashKey    : 'id',
  timestamps : true,
  schema : Joi.object().keys({
    id : Joi.string()
  }).unknown()
});
```

Pass any [Joi options](https://github.com/hapijs/joi/blob/v7.2.3/API.md#anyoptionsoptions):

``` javascript
var Model = vogels.define('example-strip-keys', {
  hashKey    : 'id',
  timestamps : true,
  schema : Joi.object().keys({
    id : Joi.string()
  }).options({ stripUnknown: true })
});
```

I have not tested out all the different options so its possible something doesn't work. Are there any specific validation options that are not working for you?

**Comment by justhamade** [comment]
I did not realize you could make the schema a Joi object with .options()
