### ISSUE TITLE
Expose AWS.DynamoDB for params 

### ISSUE THREAD

**Issue by gregorskii** [ryanfitz/vogels#135]
Hi there,

We are having issues with SSL connections with Dynamo DB per:

https://github.com/aws/aws-sdk-js/issues/862

The recommended solution is to add a strict SSL HTTP connection option to the DynamoDb client:

```
var dynamodb = new AWS.DynamoDB({
    httpOptions: {agent: new https.Agent({secureProtocol: "TLSv1_method", ciphers: "ALL"}) } }))
```

Does you library support this, and are you aware of this issue/working on a fix?

Thank you

**Comment by ryanfitz** [comment]
This should work:

``` javascript
var dynamodb = new AWS.DynamoDB({httpOptions: {agent: new https.Agent({secureProtocol: "TLSv1_method", ciphers: "ALL"})
vogels.dynamoDriver(dynamodb);
```

**Comment by gregorskii** [comment]
Thanks! Will test. Assume its good unless reopened.

Appreciate the quick response. Thought it might be that, but was thrown off by the internals.dynamoDriver:

https://github.com/ryanfitz/vogels/blob/master/lib/index.js#L27
