### ISSUE TITLE
Are lists supported?

### ISSUE THREAD

**Issue by hauboldj** [ryanfitz/vogels#136]
I haven't been able to set an attribute in my schema to be a list. Is there a way to do this?
I know about sets, but I need a list.

**Comment by hauboldj** [comment]
Yes, just use Joi.array() as the type.

**Comment by ryanfitz** [comment]
For anyone else with this question. See the [document data](https://github.com/ryanfitz/vogels/blob/master/examples/nestedAttributes.js) example. 
The example has a `Movie` model which stores an array of [actors](https://github.com/ryanfitz/vogels/blob/master/examples/nestedAttributes.js#L24).
