### ISSUE TITLE
Add support for model callbacks hooks

### ISSUE THREAD

**Issue by ajsharp** [ryanfitz/vogels#142]
Ideally, it'd be super useful to be able to hook into the validation, save/create, update, remove events to implement model logic.

**Comment by ryanfitz** [comment]
Hooks are actually already supported, however the documentation is severely limited about them. There is an [example](https://github.com/ryanfitz/vogels/blob/master/examples/hooks.js) which shows how to use them.

There are `before` and `after` hooks for model methods `create`, `update` and `destroy`.
