### ISSUE TITLE
Scan returns only 1 record but it should returns 2

### ISSUE THREAD

**Issue by osi-bhushankumar** [ryanfitz/vogels#144]
This is query that I am using : 

```
    InvoiceModel.scan()
        .where('invoiceRef').equals(search)
        .exec(function (error, response) {
          if (!_.isEmpty(error)) {
            debug('error :%o ', error);
            return callback(error, null);
          }
          debug('response.Items :%o ', response.Items);
          var documents = _.pluck(response.Items, 'attrs');
          debug('documents :%o ', documents);
          debug('documents :%o ', documents.length);
          return callback(null, documents);
        });
```

It should return me 2 records but it's give me only one record.

![screenshot_2](https://cloud.githubusercontent.com/assets/14185351/13210699/b4bc026a-d957-11e5-9260-aa1e897b3b9c.png)

And this my DynamoDb, which gives me two result.

![screenshot_3](https://cloud.githubusercontent.com/assets/14185351/13210724/fb5e2504-d957-11e5-808b-da40534ca252.png)

**Comment by tielur** [comment]
How is `search` defined?

**Comment by ryanfitz** [comment]
From your screenshot it looks like you are scanning a secondary index. Currently, vogels does not support scanning secondary indexes. See #137 for more info.

The reason you are getting only 1 record is the scan is happening against the table, the scan operation is reading all items in the table, but only 1 record matches that invoiceRef before a full page of data has been read (1MB limit).

**Comment by osi-bhushankumar** [comment]
@ryanfitz 

But AWS Dashboard return 2 records for that. How can it possible ?

**Comment by ryanfitz** [comment]
@osi-bhushankumar are you familiar with global secondary indexes versus the table primary key and how scans / queries work against them?

**Comment by set-killer** [comment]
How about performing a retry with `.loadAll()` ?

@ryanfitz: if the items that have been read exceeds 1MB, We have to use the last evaluated key like [this example](http://stackoverflow.com/questions/34407017/use-vogels-js-to-implement-pagination/34428286#34428286). Is that right?

Update: oops, consistent read is different than `.loadAll()`. But I am still guessing that loadAll() will do the job...

**Comment by osi-bhushankumar** [comment]
It was exceeded 1MB.
I uses last evaluated key for perfect output.
Thank you.
