### ISSUE TITLE
Mixed schema type

### ISSUE THREAD

**Issue by srkimir** [ryanfitz/vogels#150]
Is there something like mixed schema type like in MongoDB: http://mongoosejs.com/docs/schematypes.html

How to save something like

```
{
   a: 10,
   b: {
      c: 12,
      d: 'vogels'
   }
}
```

```
{
   a: 90,
   b: {
      p: 44,
      q: 'dynamodb'
   }
}
```

The point is i can't predict which keys nested object `b` will have

**Comment by set-killer** [comment]
For situations like this I use the `Joi.any()` type.
https://github.com/hapijs/joi/blob/v8.0.4/API.md#any

**Comment by srkimir** [comment]
@set-killer thank you on response, but it is not about type of the field, i can't predict will field exists or not and if it will exists i don't know name for it. And if i don't specify everything that **may** exists with appropriate type, vogels will throw validation error

**Comment by set-killer** [comment]
```
schema: {
  a: Joi.number(),
  b: Joi.any()
}
```

This works for me...

**Comment by set-killer** [comment]
Okey, if you absolutely don't have any schema (except an ID maybe), you can use the following schema:

```
  schema : Joi.object().keys({
    id : Joi.string()
  }).unknown()
```

Here is [the example](https://github.com/ryanfitz/vogels/blob/master/examples/dynamicKeys.js).

**Comment by srkimir** [comment]
@set-killer thank you! that i was looking for, i will close this issue
