### ISSUE TITLE
Does vogels support deletedAt?

### ISSUE THREAD

**Issue by justinmchase** [ryanfitz/vogels#175]
I'm using `useTimestamps: true` on my tables. When I delete an object, I was thinking it would just set `deletedAt: new Date()` but I'm not sure how to verify this or query deleted items.

If it doesn't do this it would be nice if it did! Or at least have `.delete()` and `.destroy()`.

**Comment by sylwit** [comment]
Hi @justinmchase 

I also did a softDelete so I add this function

```
User.prototype.softDelete = function () {
  return new Promise((resolve, reject) => {
    this.set({'deletedAt': this.get('deletedAt') || new Date().toISOString()});

    this.update(null, function (err, item) {
      if (err) {
        reject(err);
      }

      resolve(item);
    });
  });
};
```

now you can query with

`User.scan().where('deletedAt').null();`
or 
`User.scan().where('deletedAt').notNull();`

**Comment by justinmchase** [comment]
That's what we ended up doing also! Thanks for the follow up and snippet.
