### ISSUE TITLE
Rookie question

### ISSUE THREAD

**Issue by tony-gutierrez** [ryanfitz/vogels#177]
Can I not access attributes on my model instance after instantiation? Do I have to go through .attrs?? 

```
var user = new User({name:'tony');
console.log(user.name); //undefined
console.log(user.attrs.name); //tony

```

**Comment by set-killer** [comment]
Usually you have to use:

```
user.get('name');
```

[Documentation!](https://github.com/ryanfitz/vogels#saving-models-to-dynamodb)

**Comment by tony-gutierrez** [comment]
Thanks. I wish there was a way to avoid that and be more mongoose like.
