### ISSUE TITLE
[Question] Insert into dynamoDB with a duplicate hash key

### ISSUE THREAD

**Issue by srv89** [ryanfitz/vogels#178]
Currently if there is duplicate key, then data is overwritten, is it possible to configure vogels in such a a way that it throws an error, so that the data is not overwritten

**Comment by hariom12** [comment]
While the time of inserting you just add the conditional expression:-
For reference check the below link.
http://docs.aws.amazon.com/amazondynamodb/latest/gettingstartedguide/GettingStarted.JsShell.03.html

**Comment by srv89** [comment]
Thanks @hariom12 . It is clearly mentioned in the docs as well

```
User.create({id : 123, name : 'Kurt Warner' }, {overwrite : false}, function (error, acc) { ... });
```
