### ISSUE TITLE
Can a model have fields that are ignored for writes

### ISSUE THREAD

**Issue by simoami** [ryanfitz/vogels#194]
I have a model to which I assign stats. stats is a dynamically generated field but not part of the db structure. is there a way to handle this type of requirement?

**Comment by set-killer** [comment]
Yes, in your schema use `stats: Joi.any()` or `stats: Joi.object()`. Here are some [docs](https://github.com/hapijs/joi/blob/v9.2.0/API.md).

**Comment by simoami** [comment]
great, thanks! I thought I saw it something before.
