### ISSUE TITLE
"Table Created" but not visible in DynamoDB online

### ISSUE THREAD

**Issue by riyer15** [ryanfitz/vogels#197]
I'm creating a table with
```vogels.createTables(function(err) {
  if (err) {
    console.log('Error creating tables: ', err);
  } else {
    console.log('Tables has been created');
  }
});
``` 

and after running my file I get no errors. When I check on DynamoDB, however, there is no table. I declare the table like this: 

```var vogels = require('vogels');
var Joi = require('joi');
var AWS = require('aws-sdk');


vogels.AWS.config.loadFromPath('config.json'); 
var User = vogels.define('User',{
	hashKey: 'username',
	timestamps: true,
	schema : {
    email   : Joi.string().email(),
    name    : Joi.string(),
    age     : Joi.number(),
    hometown : Joi.string(),
    affiliation : Joi.string()
  }
})
```

**Comment by set-killer** [comment]
First - there is a line missing in your examples.
Second - your hash key `username` is missing from your schema. What is the type of `username` ?

Do you see the console log `Tables has been created` in your terminal?

**Comment by set-killer** [comment]
If you resolved your problem you may close this issue.

**Comment by riyer15** [comment]
Resolved! Issue had to do with the lack of username in schema.
