### ISSUE TITLE
How to check the type of a vogels model instance?

### ISSUE THREAD

**Issue by aneilbaboo** [ryanfitz/vogels#203]
What is the recommended way to determine if a given object is an instance of a vogel model?

I.e., what should I replace the instanceof expression with in the following:
```javascript
var vogels = require('vogels');

var Account = vogels.define('Account', { ... });
var myaccount = new Account({});
if (myaccount instanceof Account) {
  ...
}
```

**Comment by set-killer** [comment]
Google is your friend:
http://stackoverflow.com/questions/1249531/how-to-get-a-javascript-objects-class

**Comment by aneilbaboo** [comment]
Ugh.  Tried so many things, and forgot about .constructor.  Thanks.

For the record, in case anyone searches for this, the answer is:

```javascript

if (myaccount.constructor == Account) {
  ...
}
```
