### ISSUE TITLE
Secondary Index - ValidationException: The provided starting key is invalid

### ISSUE THREAD

**Issue by stanyq4** [ryanfitz/vogels#211]
I have a vogels model with the following schema: 

    Stock: {
       ID: String, (Hash)
       DateUTC: String (Secondary Index) 
     }

if I try to do: 

    const query = Stock.query('VOD.XLON');

and load all of the items, since I have about 5000 of them: 

    query.loadAll();
    query.exec((err, result) => {});

I get the error: ValidationException: The provided starting key is invalid.

Is there anything I am doing wrong on my side, or maybe vogels doesn't work well with loading all items that have secondary indices?

**Comment by set-killer** [comment]
Well, there is a difference between Hash key, Range key and secondary indexes.

This is a quote from the documentation of Vogels:
> For models that use hash and range keys Vogels provides a flexible and chainable query api

From the little information that you give about your schema i assume you don't have Range key.


[AWS Documentation for Primary Keys.](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/WorkingWithTables.html#WorkingWithTables.primary.key)
[AWS Documentation for Secondary Indexes.](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/SecondaryIndexes.html)
Also search for the best practices and use cases with this database.

---

const query = Stock.query('VOD.XLON'); 
Why const tho?

**Comment by stanyq4** [comment]
@set-killer I solved it by adding index to the vogels model:     

```
indexes: [{
        hashKey: 'DateUTC', name: 'stock_index', type: 'global'
    }],
```
