### ISSUE TITLE
Vogels is getting stuck when Dynamodb call timeouts

### ISSUE THREAD

**Issue by mohit2104** [ryanfitz/vogels#213]
I have updated the httpOptions and maxRetries config of aws-sdk as given below.

`"httpOptions": {
    timeout: X
}, "maxRetries": 1`

If I decrease the timeout to the extent where the dynamoDB call takes more time than X, no error is received in the callback and the handler keeps on waiting for a response.

**Comment by mohit2104** [comment]
In utils.js, For the function utils.paginatedRequest.doFunc.runRequestFunc 

`if(err && err.retryable)` condition is causing the database call to occur recursively until a response is encountered.

By removing that condition, I am finally able to get the timeout error.

**Comment by surajwy** [comment]
@ryanfitz 
Why there is a need for Vogels to have its own retry logic which infinitely blocks the callback when AWS is down. Shouldn't Vogels just act as a proxy and pass back the error to the application?
