### ISSUE TITLE
data export

### ISSUE THREAD

**Issue by ryanfitz** [ryanfitz/vogels#4]
Currently, backing up data in DynamoDB is very challenging. I want an export feature to run a parallel scan and stream the json data to a writeable stream.

**Comment by wilsonwc** [comment]
dynamo-archive is what I use for backing up data, seems to have most the features that you want including throttling so the read-rate for your table isn't exceeded.

**Comment by ryanfitz** [comment]
Yep, there are better options available now for backing up data. I'm closing this out as I don' think vogels is the right place for this functionality.
