### ISSUE TITLE
Allow reconfiguration of DynamoDB endpoint (support for DynamoDB Local)

### ISSUE THREAD

**Issue by sebdah** [ryanfitz/vogels#40]
It would be great to have a way to define the DynamoDB endpoint as I'd like to use DynamoDB local when running tests. An example configuration can be found here:

http://stackoverflow.com/questions/19868938/how-i-can-work-with-amazons-dynamodb-local-in-node

**Comment by srkimir** [comment]
probably this one needs to be updated, now im using it like:

```
vogels.AWS.config.update({
  accessKeyId: ...
  secretAccessKey: ...
  region: ...

  // http://docs.aws.amazon.com/general/latest/gr/rande.html
  endpoint: process.env.endpoint || 'http://localhost:8000'
})
```
