### ISSUE TITLE
Passing in region from vogels.AWS.config.update isn't working

### ISSUE THREAD

**Issue by aaronn** [ryanfitz/vogels#52]
I'm not doing anything other than loading in my credentials from a json file:

    vogels.AWS.config.loadFromPath('./credentials.json');

This is my credentials file:

    {"accessKeyId": "key", "secretAccessKey": "secret", "region": "us-west-1"}

When I try to connect to the db, I'm getting this regardless of what region I put in:

    [ConfigError: Missing region in config]

**Comment by divyansh-gupta** [comment]
I am seeing the same issue, wondering if you found a fix @aaronn?

**Comment by ryanfitz** [comment]
@divyansh-gupta the region must be explicitly set.

``` javascript
vogels.AWS.config.update({region: "REGION"}); // region must be set
```

See the top of the README for more details.

**Comment by nullvectorlabs** [comment]
I was facing the same problem. The issue for me was defining my models before actually setting the region itself.

After require('vogels'), you have to set the region before doing anything else.
