### ISSUE TITLE
Make logging optional

### ISSUE THREAD

**Issue by dmkelly** [ryanfitz/vogels#58]
I'm using this module and it generates noise in our logs when it creates a table. I'd like to have the ability to disable this logging. Would you be open to a pull request that uses the debug module for enabling logging based on environment variable settings?

**Comment by ryanfitz** [comment]
Yes, improved logging support is definitely something I want to support. I'm planning on adding full logging support (using bunyan) which will give users the ability to tune logging levels and be able to turn off logging completely.

**Comment by focusaurus** [comment]
+1. Libraries writing to stdout by default is a big no-no. The [debug](https://www.npmjs.com/package/debug) package would be a decent quick stop-gap.
