### ISSUE TITLE
Sanitization like Mongoosejs

### ISSUE THREAD

**Issue by tielur** [ryanfitz/vogels#61]
What's your thoughts on adding something similar to what mongoose has that only saves input that is a part of the schema? I need to sanitize input before saving the model using vogels. I thought about using something like this using lodash, which would work, but it would be nice if this was built into vogels.

```js
var _ = require('lodash');

// in a user create express route...
var userData = _.pick(req.body, 'email', 'name', 'username', 'title');
User.create(userData, function (err, user) {
  console.log('created account in DynamoDB', user.get('email'));
});
```

This would only save the email, name, username, and title to the user. Even if something like `admin: true` was in the body.

I know mongoosejs has a [strict](http://mongoosejs.com/docs/guide.html#strict) implementation that might be interesting in vogels.

Thoughts?

**Comment by tielur** [comment]
On second review I think this is two different things. 
1. Is to prevent data that was not a part of the schema from being saved.
2. Is to prevent **certain** data that **is** a part of the data being saved, like an admin flag

**Comment by ryanfitz** [comment]
This is actually already supported.  Here is an example schema definition which will strip unknown attributes before creating a record

```js
var schema = Joi.object().keys({
    username: Joi.string().alphanum().min(3).max(30).required(),
    password: Joi.string().regex(/[a-zA-Z0-9]{3,30}/),
    access_token: [Joi.string(), Joi.number()],
    birthyear: Joi.number().integer().min(1900).max(2013),
    email: Joi.string().email()
}).options({ stripUnknown : true });
```
