### ISSUE TITLE
Item.save does not respect timestamps

### ISSUE THREAD

**Issue by flowhamster** [ryanfitz/vogels#62]
I noticed that Item.save is not setting the updatedAt column for items with a schema of timestamps = true.

**Comment by ryanfitz** [comment]
This is working as I intended, but perhaps thats not what others would expect? 

When `timestamps = true` is set, when calling `item.save` the attribute createdAt will get set with the current timestamp of the save. The attribute `updatedAt` will get created only when calling `Item.update`. I should better explain this in the readme.
