### ISSUE TITLE
Better retry logic

### ISSUE THREAD

**Issue by tielur** [ryanfitz/vogels#63]
It looks like vogels implements retry logic if a request fails, but it seems to just hammer the dynamoDB api until it either fails or gets a success. According to amazon something like an exponential backoff should be followed when getting an error that is retry-able.

References:
[Vogel Retry Logic](https://github.com/ryanfitz/vogels/blob/master/lib/batch.js#L70)
[Amazon Exponential Backoff](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ErrorHandling.html#APIRetries)

Thoughts?

**Comment by ryanfitz** [comment]
retry logic and exponential backoff are currently handled by the aws-js sdk. You can look at the aws-js sdk for more info on how this is handled.

**Comment by tielur** [comment]
ahh ok thanks!
