### ISSUE TITLE
Status for the IN operator?

### ISSUE THREAD

**Issue by jtpio** [ryanfitz/vogels#64]
What is the status regarding the IN operator?

The IN operator is documented on the main page in the [scan section](https://github.com/ryanfitz/vogels/blob/master/README.md#scan), but apparently the corresponding test is [still disabled](https://github.com/ryanfitz/vogels/blob/master/test/scan-test.js#L293).

I have tried to use the IN operator based on the example code, but it raises a ValidationException.

Executing this:
```js
'use strict';

var AWS = require('aws-sdk');
var vogels = require('vogels');
var Joi = require('joi');

AWS.config.update({
	accessKeyId: 'accessKeyId',
	secretAccessKey: 'secretAccessKey',
	region: 'region'
});

vogels.dynamoDriver(new AWS.DynamoDB({ endpoint: 'http://localhost:8000' }));

var Account = vogels.define('Account', {
  hashKey : 'email',

  // add the timestamp attributes (updatedAt, createdAt)
  timestamps : true,

  schema : {
    email   : Joi.string().email(),
    name    : Joi.string(),
    age     : Joi.number(),
    roles   : vogels.types.stringSet(),
    settings : {
      nickname      : Joi.string(),
      acceptedTerms : Joi.boolean().default(false)
    }
  }
});

Account.config({tableName: 'AccountsTable'});

vogels.createTables({
  'example-Account'  : {readCapacity: 1, writeCapacity: 10},
}, function (err) {
  if(err) {
    console.log('Error creating tables', err);
    process.exit(1);
  }

  Account.create({email: 'foo@example.com', name: 'Foo Bar', age: 21}, function (err, acc) {
	  console.log('created account in DynamoDB', acc.get('email'));
	  Account
		  .scan()
		  .where('name').in(['foo@example.com', 'bar@example.com'])
		  .exec(function (err, accounts) {
		  	console.log('Error:', err);
		  	console.log('Accounts:', JSON.stringify(accounts));
		  });
	});
});
```
Gives this output:
```
created account in DynamoDB foo@example.com
Error: { [ValidationException: One or more parameter values were invalid: ComparisonOperator IN is not valid for L AttributeValue type]
  message: 'One or more parameter values were invalid: ComparisonOperator IN is not valid for L AttributeValue type',
  code: 'ValidationException',
  time: Wed Mar 18 2015 16:24:17 GMT+0100 (W. Europe Standard Time),
  statusCode: 400,
  retryable: false,
  retryDelay: 0 }
Accounts: undefined
```

Should the IN operator be removed from the documentation if it is not possible to use it?

**Comment by haritonstefan** [comment]
Hello, the same exception here.
Has someone found a solution for this?

**Comment by justhamade** [comment]
I also ran into the same issue.  If this issue wasn't here would have been banging my head for a lot longer.

**Comment by Incubatio** [comment]
Same here, glad I checked the issues.
@ryanfitz -> it's reported since march, come on man at least put something in readme, it's like 3 seconds to commit/push that.

**Comment by Incubatio** [comment]
To make a IN you can use FilterExpression or ConditionExpression:
```js
   var query = User.scan()
     .filterExpression("#v IN ( #1, #2)")
     .expressionAttributeNames({'#v' : 'id'})
     .expressionAttributeValues( '#1': 1, '#2': 2 )
```
a not in with:
```js
.filterExpression("NOT #v IN ( #1, #2)")
```
@ryanfitz put an example in README.MD with BETWEEN and begin_with for scan. 

Here is doc on syntax of FilterExpression/ConditionExpression:
http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.SpecifyingConditions.html#ConditionExpressionReference

**Comment by Incubatio** [comment]
Thanks for the updates @ryanfitz :).
