### ISSUE TITLE
Issue with package.json dynamodb-doc dependency

### ISSUE THREAD

**Issue by nickpestov** [ryanfitz/vogels#66]
When I npm install vogels (2.0.0-rc9), the package.json under node_modules/vogels has this dependancy:

"dynamodb-doc": "git+https://github.com/awslabs/dynamodb-document-js-sdk"

It requires git and causes problems when deploying to Elastic Beanstalk on AWS.

**Comment by damienwhaley** [comment]
I've created a pull request which should resolve this issue:

https://github.com/ryanfitz/vogels/pull/71

**Comment by pursual** [comment]
This is closed, no?
