### ISSUE TITLE
On create(), createdAt is returned as an integer; on subsequent update both createdAt and updatedAt come back as ISO date strings

### ISSUE THREAD

**Issue by keithchilders** [ryanfitz/vogels#77]
Steps to reproduce:

enable timestamps on model
model.create({foo:'bar'}) returns:

{ id: 'some-generated-id', foo: 'bar', createdAt: 1438116381811 }

now model.update({id:'some-generated-id', foo:'baz'}) returns:

{id: 'some-generated-id', foo: 'baz', createdAt: "2015-07-28T20:43:40.179Z", updatedAt: "2015-07-28T20:47:48.688Z" }

it looks like the serializer is only casting javascript date values to strings on update, not on create?

**Comment by keithchilders** [comment]
It appears this is just an issue with the data that create() and update() methods send to the callback function. The data goes into dynamodb as a string regardless.

**Comment by JoshZA** [comment]
:+1:  this is super irritating
