### ISSUE TITLE
vogels.types is undefined

### ISSUE THREAD

**Issue by mgenev** [ryanfitz/vogels#79]
The docs refer to vogels.types including for generating the uuid, but when I try I get this:
```
/Users/mgenev1271/Projects/ape-poll-service/util/create-dev-db.js:32
    question_id : vogels.types.uuid(),
                              ^

TypeError: Cannot read property 'uuid' of undefined
```

also when I clone this repo and try to run the tests with, all unit tests pass, but all integration tests fail with this error:
```
  Uncaught AssertionError: expected [ConfigError: Missing region in config] to not exist
```

**Comment by sharavsambuu** [comment]
same issue here, did u solved your problem?

**Comment by jotham** [comment]
Hey guys, make sure your vogel's version actually contains this call (just grep node_modules/vogels/)
