### ISSUE TITLE
Version Issue

### ISSUE THREAD

**Issue by christopheretcheverry** [ryanfitz/vogels#81]
Just FYI npm install vogels pulls down an older version (0.12.0) with issues out of the box.

    callback(schema);
    ^
TypeError: object is not a function

```
vogels.define = function (modelName, callback) {
  var schema = new Schema();

  var compiledTable = internals.compileModel(modelName, schema);

  console.log(callback);
  console.log(callback.inspect);
  if(callback) {
    callback(schema);
  }

  return compiledTable;
};
```

**Comment by JoshZA** [comment]
I just ran into this, npm installed:     "vogels": "^0.12.0"

**Comment by devinus** [comment]
This is because `vogels` latest is an RC, which `npm` wont install by default.

**Comment by Incubatio** [comment]
in package.json, you can put: 
"vogels": "^2.0.0-rc10"

But yeah, this need to be fixed.

**Comment by bugeats** [comment]
I'm trying out vogels for a new project and this just caused me a lot of confusion.  I found myself reconsidering the whole idea.

**Comment by devinus** [comment]
Development unfortunately seems abandoned when you've had an rc since July.

**Comment by bugeats** [comment]
Yeah, screw it. I'm outta here. I'll just wrap AWS SDK calls myself.
