### ISSUE TITLE
Support add any property without property definition in table definition

### ISSUE THREAD

**Issue by flyingsky** [ryanfitz/vogels#84]
For exmpale I have table Foo with id, name and defined in model. The problem is that I cannot save any extra column into dynamodb if I don't define a new column in model. This is not NonSql if we have to define any column.

If some column is not defined we can save it directly based on the value type.

**Comment by set-killer** [comment]
Hello,

For columns with multiple type options you can use the type `Joi.any()`. 
Don't forget that this is an Object-Document Mapper (ODM) library. For this 'mapping' functionality there must be some kind of schema.

If you don't want to define any columns then you must use the `aws-sdk` package, provided by Amazon.

**Comment by flyingsky** [comment]
Even mapper library, there is still a way to deductive column type without definition. I don't mean no table definition, but maybe it's possible to make the definition simpler, just define the key columns, like the hash key column and global index columns like aws-sdk. As other columns depends on user's preference.

**Comment by ryanfitz** [comment]
@flyingsky This is fully supported - see the [dynamic keys example](https://github.com/ryanfitz/vogels/blob/master/examples/dynamicKeys.js). In that example only the id param is defined, but then other attributes get saved to records.

**Comment by flyingsky** [comment]
Do you mean have to call "unknown" method?
